---
- hosts: Host_Name_IP

  vars_prompt:
  - name: user_name
    prompt: "user_name"
    private: no

  - name: "new_password"
    prompt: "Enter New Password"
    private: yes
    encrypt: "md5_crypt"
    confirm: yes
    salt_size: 7

  tasks:
    - name: Change password of existing user
      user: name={{ user_name }} update_password=always password={{ new_password }}

    - name: Expiry of password
      command: chage -d 0 {{ user_name }}

    - name: Queries for alter password
      action: shell echo -e "ALTER USER {{ user_name }} WITH PASSWORD '{{ new_password }}';" | su postgres -c "psql"
